### ISSUE TITLE
auto page build

### ISSUE THREAD

**Issue by Gnosnay** [Evian-Zhang/introduction-to-linux-x86_64-syscall#2]
有兴趣使用 https://github.com/peaceiris/actions-mdbook 来进行 auto page build 吗？
最后的页面 host 在个人 github.io 主页上，大概是 username.github.io/repo-name/path 的样子

**Comment by Evian-Zhang** [comment]
由于README里超链接的原因，mdbook目前版本会出一些问题，已经给他们提了PR（ https://github.com/rust-lang/mdBook/pull/1466 ），等官方合并了之后就可以了。

**Comment by Gnosnay** [comment]
这个issue看起来maintainer没关注啊🤔，，看看有没有什么其它办法催一下hh
